version: '3.8'

services:
  app:
    build:
      context: ./docker/php
    container_name: gameboxd-app
    volumes:
      - .:/var/www
    depends_on:
      - postgres
      - redis
    networks:
      - gameboxd

  nginx:
    image: nginx:alpine
    container_name: gameboxd-nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - gameboxd

  postgres:
    image: postgres:15
    container_name: gameboxd-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: gameboxd
      POSTGRES_USER: gameboxd
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - gameboxd

  redis:
    image: redis:alpine
    container_name: gameboxd-redis
    ports:
      - "6379:6379"
    networks:
      - gameboxd

volumes:
  pgdata:

networks:
  gameboxd:
    driver: bridge
